### ISSUE TITLE
Unable to load model

### ISSUE THREAD

**Issue by omrishsu** [Iddoyadlin/hebrew-w2v#1]
when i try to load the model:
model_w2v = Word2Vec.load('/home/hebrew-word2vec/wiki_tokenized_model/model.mdl')
i get:
`_pickle.UnpicklingError: invalid load key, '\x00'.`

on:
`return _pickle.load(f, encoding='latin1')`
in:
`gensim.utils.unpickle`

any idea what is missing here?

**Comment by Iddoyadlin** [comment]
@omrivm I'm using windows 11, python 3.9.10 and gensim 4.1.2 (installed in venv). what are you using? what does the following output:
1. pip show gensim
2. python --version

**Comment by omrishsu** [comment]
@Iddoyadlin found the problem. For some reason, the rar file is extracted ok on windows, but on ubuntu, it is extracted corrupted.

**Comment by Iddoyadlin** [comment]
@omrivm were you able to extract it on ubuntu? care to share how you did it?

**Comment by omrishsu** [comment]
No, i was not able to do that. I've extracted it on windows and transfer the mdl file to ubuntu.
